cloud:
  aws:
    credentials:
      access-key: AKIAVVYXUSX2ER6JZETC
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: pruebacx

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090